[package]
name = "web_server"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
privdrop = "0.5.2"
anyhow = "1.0"
rocket = { version = "0.5.0-rc.2", features = ["tls"] }
